version: '3'

services:
  broker-service:
    container_name: "broker"
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./../broker-service:/app/brokerDir # 掛載檔案
    working_dir: /app/brokerDir/cmd/api # 一進入 container 會在哪個 dir
    deploy:
      mode: replicated
      replicas: 1